// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using user_api_csharp.src.Data;

#nullable disable

namespace user_api_csharp.src.Migrations
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

      modelBuilder.Entity("user_api_csharp.src.Models.User", b =>
        {
          b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("INTEGER");

          b.Property<string>("Email")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("TEXT");

          b.Property<DateTime>("DateOfBirth")
            .HasColumnType("TEXT");

          b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.HasIndex("Email")
            .IsUnique();

          b.ToTable("Users");
        });
#pragma warning restore 612, 618
    }
  }
}
